# Generated by Django 5.1.3 on 2024-11-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='score',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_history', to='src.question'),
        ),
        migrations.AlterField(
            model_name='history',
            name='team',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_history', to='src.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='question',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_got_question', to='src.question'),
        ),
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
