# Generated by Django 5.1.3 on 2024-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_team_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='flag',
            field=models.CharField(max_length=32),
        ),
    ]
