# Generated by Django 5.2.17 on 2026-10-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('secret', models.CharField(max_length=8, unique=True)),
                ('duration', models.IntegerField(default=120)),
                ('statement', models.TextField()),
                ('task', models.TextField()),
                ('exp_output', models.TextField()),
                ('typical_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_question_table',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_got_question', to='main.question')),
            ],
            options={
                'db_table': 'app_team_table',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('flag', models.CharField(max_length=32)),
                ('score', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_history', to='main.question')),
                ('team', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_history', to='main.team')),
            ],
            options={
                'db_table': 'app_history_table',
                'ordering': ['timestamp'],
            },
        ),
    ]
