# Generated by Django 5.1.3 on 2024-11-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8)),
                ('secret', models.CharField(max_length=8, unique=True)),
                ('duration', models.IntegerField(default=120)),
                ('statement', models.TextField()),
                ('task', models.TextField()),
                ('exp_output', models.TextField()),
                ('typical_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_question_table',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_got_question', to='src.question')),
            ],
            options={
                'db_table': 'app_team_table',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('flag', models.CharField(max_length=32, unique=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_history', to='src.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_history', to='src.team')),
            ],
            options={
                'db_table': 'app_history_table',
                'ordering': ['timestamp'],
            },
        ),
    ]
