# Generated by Django 5.1.3 on 2024-11-10 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='question_number',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='team_code',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='question_number',
        ),
        migrations.AddField(
            model_name='team',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_got_question', to='src.question'),
        ),
    ]
