# Generated by Django 5.1.3 on 2024-11-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_question_number_history_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='question',
            new_name='score',
        ),
    ]
