# Generated by Django 5.1.3 on 2024-11-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_history_score_alter_history_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='question',
            field=models.ForeignKey(db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_got_question', to='src.question'),
        ),
    ]
