# Generated by Django 5.1.3 on 2024-11-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_team_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(blank=True, default='', max_length=32, null=True, unique=True),
        ),
    ]
